### ISSUE TITLE
Timing Issue when using `externalConsole: false`

### ISSUE THREAD

**Issue by AE1020** [penagos/vgdb#14]
I am trying vgdb on [this simple example case in vscode-cpptools issue 5235](https://github.com/microsoft/vscode-cpptools/issues/5235) *(as I had it on hand from looking at that debugging issue...)*

vgdb didn't work--just hung, not hitting the breakpoint.  So I decided I'd try building the vgdb extension and seeing if I could figure out why not.  

*However* once I started running vgdb under extension debugging it did occasionally work.  Then I found that I could get it to always work by setting a breakpoint on the call to [`new IntegratedTerminal(launchCommand, terminal);`](https://github.com/penagos/vgdb/blob/3eff76c107561b427fe1c0894a90c578b6d3b501/src/debuggers/Debugger.ts#L235)...then stepping over it...then hitting continue.

Looking in the running processes list it doesn't seem `new IntegratedTerminal` alone has started gdb either way.  But having the delay introduced by debugging at that point does seem to make the difference between whether it works out later or not.  When it is the hung state, there is no gdb process started when looking in the processes with `ps`--but it thinks it has sent several commands and is in a state of waiting for a response.  (The successful state obviously has a gdb process started.)

I thought to try changing to `externalConsole: true` so it doesn't make an IntegratedTerminal.  In doing so, I don't have to disrupt the timing via a breakpoint to get it to work.

*(Sidenote: once I got vgdb to run, it also manifests issue 5235 [for the same reasons](https://github.com/microsoft/vscode-cpptools/issues/5235#issuecomment-941828993))*

**Comment by penagos** [comment]
The issue seems to be not waiting for the GDB process to be in a ready state prior to sending commands. Right now I incorrectly assume the GDB process spawn and terminal spawn to be atomic in nature, when in reality they could take a variable amount of time, hence the sporadic nature. I'll need to query GDB at start and spin until the prompt is emitted to the `stdout` buffer.

**Comment by penagos** [comment]
I've dug into this a bit more, and from my initial testing, 93a457c43d22543c84d6c8e5c069016582f97135 seems to have resolved the issue. I'll test it out more this weekend with a couple of different programs though as of now it looks promising.
