### ISSUE TITLE
Stoped working on vscode 1.67.1 version

### ISSUE THREAD

**Issue by iwasz** [penagos/vgdb#19]
Hey, I noticed a strange behavior of the plugin on vscode version 1.67.1 (prior to this ver. it was OK). Instead of running in the dedicated "debug console" pane the session starts in the built in terminal. What's more, the debugging stops immediately and you have to input "run" to move forward. Variables and call stack views are empty, the debugging toolbar allows only for stopping or restarting (pause button is inactive). I haven't changed my lauch.json. My config:

        {
            "type": "vgdb",
            "request": "launch",
            "name": "C/C++ Debug Launch - vGdb",
            "program": "${command:cmake.launchTargetPath}",
        },

**Comment by iwasz** [comment]
It might be a problem with vscode itself though, because other debugger plugins misbehave as well. "Error opening terminal: unknown." is often displayed.

**Comment by penagos** [comment]
Yes; there was a recent regression in 1.67 and multiple extensions which rely on redirecting STDIO in the integrated terminal have stopped working (see https://github.com/microsoft/vscode/issues/148887). From the looks of it, the fix (https://github.com/microsoft/vscode/pull/149284) should be landing next week in 1.67.2. I'll close this once I verify the extension works again with this build.

**Comment by penagos** [comment]
I've just confirmed the extension works properly on the just-released 1.67.2 build: https://github.com/microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22April+2022+Recovery+2%22+is%3Aclosed

As such, closing this issue.
