### ISSUE TITLE
Allow to pass options to gdb

### ISSUE THREAD

**Issue by tmokmss** [penagos/vgdb#20]
Hi thank you very much for developing this great extension! It's working so nicely 😄 

One question is that, is it possible to pass gdb CLI options from vgdb?

In my use case (debug of MariaDB), I need to pass `-x` option to execute startup commands from a file, like the below command:

```sh
gdb -x /home/ec2-user/MariaDB-server/bld/mysql-test/var/tmp/gdbinit.mysqld.1   /home/ec2-user/MariaDB-server/bld/sql/mysqld
```

Because the content of `gdbinit.mysqld.1` won't dynamically change, currently I'm copy and pasting the content to `startupCmds` option in `launch.json` as a workaround. But ideally it can be passed by `-x` option.

Is there any way already implemented to achieve this? Thanks!

**Comment by tmokmss** [comment]
Hi, I guess your suggestion will work in my case. Or we can add a config value like `cmdOptions` that can just append arbitrary cli options to `gdb` command. Either is fine for me, thanks!

**Comment by penagos** [comment]
This has been completed and will be included in the next point release with a couple of other bug fixes / improvements. The proposed API is:

```
debuggerArgs: [
    '--arg1',
    '--arg2'
]
```

In your debug launch configuration JSON file. These arguments will be passed directly to GDB on launch, i.e.:

```
gdb --arg1 --arg2
```
